features=["driver_cancellation_rate","acceptance_rate","driver_completed_ratio"]
target="is_completed"
test_size=0.2

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false
class_weight = "balanced"
